services:
  - type: web
    name: racksephnox
    runtime: docker
    plan: starter
    region: frankfurt
    branch: spiral
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: Racksephnox
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://racksephnox.onrender.com
      - key: ASSET_URL
        value: https://racksephnox.onrender.com
      - key: APP_KEY
        sync: false
      - key: APP_TIMEZONE
        value: Africa/Nairobi
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_STACK
        value: stderr
      - key: LOG_LEVEL
        value: warning
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_DOMAIN
        value: null
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: BROADCAST_CONNECTION
        value: log
      - key: MAIL_MAILER
        value: log
      - key: RUN_MIGRATIONS
        value: true
      - key: RUN_SEEDERS
        value: false
    disk:
      name: racksephnox-data
      mountPath: /var/www/html/database
      sizeGB: 1
